services:
  - type: web
    name: rexxailabs-api
    env: node
    buildCommand: bash ./build.sh
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: NODE_ENV
        value: production